# Generated by Django 3.2 on 2021-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.EmailField(db_index=True, max_length=254, verbose_name='Автор')),
                ('massage', models.CharField(max_length=1024, verbose_name='Сообщение')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
