# Generated by Django 3.2 on 2021-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_db2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='massage',
            field=models.TextField(max_length=1024, verbose_name='Сообщение'),
        ),
    ]
